"""kaos-citations — structured, high-performance citation
identification and extraction for KAOS.

Text in, typed :class:`Citation` records out. Frozen Pydantic models
with ``raw`` / ``normalized`` / ``span`` provenance, Bluebook
modifiers, and family-specific structured fields. Recognises 60
citation ``kind`` literals across legal, financial, accounting, and
identifier domains. Pure-Python, fully offline, deterministic,
Rust-backed matching via ``kaos-nlp-core``.

This package does NOT do citation resolution (URL building, body
fetching) or claim verification. Those concerns live in the rest of
the KAOS stack:

- ``kaos-source`` — typed connectors to authoritative sources
  (Federal Register, eCFR, GovInfo, CourtListener via PACER, etc.)
- ``kaos-web`` — generic web search + fetch
- ``kaos-llm-core`` — typed LLM signatures including ``Cited[T]``
  grounding for in-process claim verification
- ``kaos-agents`` — orchestrates the above

Composition pattern: ``kaos-citations`` extracts; downstream agents
or kaos-source connectors fetch / verify with the typed citation as
input.
"""

from __future__ import annotations

from kaos_citations._version import __version__
from kaos_citations.errors import (
    CitationParseError,
    KaosCitationsError,
)
from kaos_citations.extract import extract_citations
from kaos_citations.model import (
    AdjudicatingAgency,
    AgencyAdjudicationCitation,
    AgencyManualCitation,
    AICPACitation,
    AICPADocKind,
    ArchiveCitation,
    ArXivCitation,
    ASCCitation,
    ASUCitation,
    BarEthicsOpinionCitation,
    BaselFrameworkCitation,
    CaseCitation,
    CaseReferenceCitation,
    CFPBDocKind,
    CFPBDocumentCitation,
    CFRCitation,
    CFTCDocKind,
    CFTCDocumentCitation,
    Citation,
    CitationBase,
    ConstitutionCitation,
    CourtDocKind,
    CourtDocumentCitation,
    DOICitation,
    ElectronicMediaCitation,
    ElectronicMedium,
    ExchangeRuleCitation,
    ExecutiveActionCitation,
    ExecutiveActionKind,
    FASABCitation,
    FASABDocKind,
    FDICDocKind,
    FDICDocumentCitation,
    FederalRegisterCitation,
    FederalRuleCitation,
    FederalRuleSet,
    FedReserveLetterCitation,
    FedReserveLetterKind,
    FedReserveRegulationCitation,
    FFIECCallReportCitation,
    FINRADisciplinaryCitation,
    FINRARegulatoryNoticeCitation,
    FINRARuleCitation,
    GASBCitation,
    GASBDocKind,
    GovernmentAuditCitation,
    GovtAuditDocKind,
    HereinafterCitation,
    IAASBCitation,
    IAASBStandardKind,
    IdCitation,
    IESBACodeCitation,
    IFRSCitation,
    IFRSStandardKind,
    InternationalFinancialCitation,
    InternetCitation,
    IntlFinancialBody,
    IRSGuidanceCitation,
    IRSGuidanceKind,
    JournalCitation,
    LegacyFASBCitation,
    LegacyFASBStatementKind,
    LegalOpinionCitation,
    LegislativeCitation,
    LegislativeDocKind,
    LocalRuleCitation,
    LocalRuleSet,
    LooseleafCitation,
    NAICAccountingCitation,
    NAICCitation,
    NAICDocKind,
    NCUALetterCitation,
    NewspaperCitation,
    OCCDocKind,
    OCCDocumentCitation,
    OpinionAuthority,
    ParentheticalKind,
    PCAOBCitation,
    PCAOBDocKind,
    PinCiteKind,
    ProfessionalConductCitation,
    PublicLawCitation,
    PubMedCitation,
    RestatementCitation,
    RestatementSeries,
    SECAct,
    SECFilingCitation,
    SECFilingForm,
    SECRegulationCitation,
    SECRegulationKind,
    SECReleaseCitation,
    SECStaffDocKind,
    SECStaffGuidanceCitation,
    SecuritiesExchange,
    ShortCaseCitation,
    SignalKind,
    StateSessionLawCitation,
    StatuteCitation,
    SubsequentHistoryRelation,
    SupraCitation,
    SustainabilityCitation,
    SustainabilityFramework,
    TreasuryRegulationCitation,
    TreasuryRegulationStatus,
    TreatiseCitation,
    TreatyCitation,
    UniformActCitation,
    UniformActShort,
    UnknownCitation,
    UnpublishedManuscriptCitation,
    USSGCitation,
    WeightOfAuthority,
    WorkingPaperCitation,
)
from kaos_citations.parsers import (
    extract_case_citations,
    extract_case_short_forms,
    extract_cfr_citations,
    extract_journal_citations,
    extract_statute_citations,
)
from kaos_citations.postprocess import (
    apply_postprocess,
    assign_cite_ids,
    attach_signals,
    attach_string_cite_groups,
    attach_subsequent_history,
)
from kaos_citations.resources import (
    CITATION_KINDS_URI,
    CitationKindsResource,
    register_citations_resources,
)
from kaos_citations.settings import KaosCitationsSettings
from kaos_citations.tools import register_citations_tools

__all__ = [
    "CITATION_KINDS_URI",
    "AICPACitation",
    "AICPADocKind",
    "ASCCitation",
    "ASUCitation",
    "AdjudicatingAgency",
    "AgencyAdjudicationCitation",
    "AgencyManualCitation",
    "ArXivCitation",
    "ArchiveCitation",
    "BarEthicsOpinionCitation",
    "BaselFrameworkCitation",
    "CFPBDocKind",
    "CFPBDocumentCitation",
    "CFRCitation",
    "CFTCDocKind",
    "CFTCDocumentCitation",
    "CaseCitation",
    "CaseReferenceCitation",
    "Citation",
    "CitationBase",
    "CitationKindsResource",
    "CitationParseError",
    "ConstitutionCitation",
    "CourtDocKind",
    "CourtDocumentCitation",
    "DOICitation",
    "ElectronicMediaCitation",
    "ElectronicMedium",
    "ExchangeRuleCitation",
    "ExecutiveActionCitation",
    "ExecutiveActionKind",
    "FASABCitation",
    "FASABDocKind",
    "FDICDocKind",
    "FDICDocumentCitation",
    "FFIECCallReportCitation",
    "FINRADisciplinaryCitation",
    "FINRARegulatoryNoticeCitation",
    "FINRARuleCitation",
    "FedReserveLetterCitation",
    "FedReserveLetterKind",
    "FedReserveRegulationCitation",
    "FederalRegisterCitation",
    "FederalRuleCitation",
    "FederalRuleSet",
    "GASBCitation",
    "GASBDocKind",
    "GovernmentAuditCitation",
    "GovtAuditDocKind",
    "HereinafterCitation",
    "IAASBCitation",
    "IAASBStandardKind",
    "IESBACodeCitation",
    "IFRSCitation",
    "IFRSStandardKind",
    "IRSGuidanceCitation",
    "IRSGuidanceKind",
    "IdCitation",
    "InternationalFinancialCitation",
    "InternetCitation",
    "IntlFinancialBody",
    "JournalCitation",
    "KaosCitationsError",
    "KaosCitationsSettings",
    "LegacyFASBCitation",
    "LegacyFASBStatementKind",
    "LegalOpinionCitation",
    "LegislativeCitation",
    "LegislativeDocKind",
    "LocalRuleCitation",
    "LocalRuleSet",
    "LooseleafCitation",
    "NAICAccountingCitation",
    "NAICCitation",
    "NAICDocKind",
    "NCUALetterCitation",
    "NewspaperCitation",
    "OCCDocKind",
    "OCCDocumentCitation",
    "OpinionAuthority",
    "PCAOBCitation",
    "PCAOBDocKind",
    "ParentheticalKind",
    "PinCiteKind",
    "ProfessionalConductCitation",
    "PubMedCitation",
    "PublicLawCitation",
    "RestatementCitation",
    "RestatementSeries",
    "SECAct",
    "SECFilingCitation",
    "SECFilingForm",
    "SECRegulationCitation",
    "SECRegulationKind",
    "SECReleaseCitation",
    "SECStaffDocKind",
    "SECStaffGuidanceCitation",
    "SecuritiesExchange",
    "ShortCaseCitation",
    "SignalKind",
    "StateSessionLawCitation",
    "StatuteCitation",
    "SubsequentHistoryRelation",
    "SupraCitation",
    "SustainabilityCitation",
    "SustainabilityFramework",
    "TreasuryRegulationCitation",
    "TreasuryRegulationStatus",
    "TreatiseCitation",
    "TreatyCitation",
    "USSGCitation",
    "UniformActCitation",
    "UniformActShort",
    "UnknownCitation",
    "UnpublishedManuscriptCitation",
    "WeightOfAuthority",
    "WorkingPaperCitation",
    "__version__",
    "apply_postprocess",
    "assign_cite_ids",
    "attach_signals",
    "attach_string_cite_groups",
    "attach_subsequent_history",
    "extract_case_citations",
    "extract_case_short_forms",
    "extract_cfr_citations",
    "extract_citations",
    "extract_journal_citations",
    "extract_statute_citations",
    "register_citations_resources",
    "register_citations_tools",
]
